# Generated by Django 2.0.3 on 2018-11-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_auto_20181110_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Grade'),
        ),
    ]
